version: '3'

services:

redis:
    image: redis:latest
    hostname: redis

web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: run_server.sh
    volumes:
      - .:/app
    ports:
      - "5000:5000"

worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: run_celery.sh
    volumes:
      - .:/app
    links:
      - redis